#!/bin/bash

for day in $(seq 1 25); do
  cat > "src/day$day.rs" <<EOF
pub fn run() -> anyhow::Result<()> {
    let input = std::fs::read_to_string("day$day.txt")?;

    println!("$day:1 - {}", run_1(&input)?);
    println!("$day:2 - {}", run_2(&input)?);

    Ok(())
}

fn run_1(_input: &str) -> anyhow::Result<usize> {
  todo!()
}

fn run_2(_input: &str) -> anyhow::Result<usize> {
  todo!()
}

#[cfg(test)]
mod tests {
    #[test]
    fn aoc1_run_1() {
    }

    #[test]
    fn aoc1_run_2() {
    }
}
EOF
done
